name: simple_bloc_observer
description: Template for Flutter Package project.
version: 0.0.1
author: Steven Smith
homepage: http://www.fhcp.com
publish_to: 'none'

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.1.0
  flutter_modular: ^3.3.1
  intl: ^0.17.0

dev_dependencies:
  test: ^1.17.10

flutter:
  uses-material-design: true
